# Setup
title:               Land use cover classification
tagline:             'Landsat images'
description:         'Project 2: Data science portafolio'
url:                 
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Cristián Vergara 
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Caching
cache: true
cache_dir: .jekyll-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mark Otto"
      image: "/assets/images/default-image.jpg"

